" Pathogen
execute pathogen#infect()
execute pathogen#helptags()

" Vim color status
set t_Co=256
set t_ut=

" Set leader
let mapleader=','

" Line number
set number relativenumber

" Syntax enable
syntax enable
syntax on

" No swap file
set noswapfile

" Set not wrap
set nowrap

" Autoindent
" set autoindent

" Set ruler
set ruler

" Tab stop & Shift width
set tabstop=4
set shiftwidth=4

" Expand tab & Soft tabstops
set expandtab
set softtabstop=4

" Search
" set hlsearch
set incsearch
set ignorecase
set smartcase

" Set tab space to 2 for javascript
autocmd Filetype javascript setlocal ts=2 sw=2 sts=0 expandtab

" Set tab space to 2 for html
autocmd Filetype html setlocal ts=2 sw=2 sts=0 expandtab

" Set max line for python
autocmd FileType python set colorcolumn=79

" Colorscheme
if exists('+termguicolors')
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
    set termguicolors
endif

set background=dark
" highlight Comment cterm=bold
" highlight clear SignColumn
" highlight ColorColumn ctermbg=237

" Gruvbox
" colorscheme gruvbox
" let g:gruvbox_contrast_dark = 'hard'
" let g:gruvbox_invert_selection='0'

" Ayu
" let ayucolor="mirage"
let ayucolor="dark"
colorscheme ayu

" Seoul256
" let g:seoul256_background = 234
" let g:seoul256_srgb = 1
" colorscheme seoul256

" Railscasts
" colorscheme new-railscasts
" colorscheme railscasts

" OceanicNext
" let g:oceanic_next_terminal_bold = 1
" let g:oceanic_next_terminal_italic = 1
" colorscheme OceanicNext

" Despacio
" let g:despacio_Sunset = 1
" colorscheme despacio

" Performance and buffer
set hidden
set lazyredraw
set ttyfast

" History
set history=999
set undolevels=999
set autoread

" Tabs
set guitablabel=\[%N\]\ %t\ %M
nnoremap <C-t> :tabnew<CR>

" Ignore files
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.pyc
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git\|__pycache__\|dict|env\'

" NERDTree ignore files
let NERDTreeShowHidden=1
let NERDTreeIgnore = ['\.pyc$', '__pycache__', '.git', '.tox']
map <F3> :NERDTreeToggle<CR>
map <C-n> :NERDTreeToggle<CR>
let NERDTreeMapOpenInTab='t'

" NERDCommenter
filetype plugin indent on
let g:NERDSpaceDelims=1
let g:NERDTrimTrailingWhitespace=1

" Status
set laststatus=2

" CtrlP
let g:ctrlp_switch_buffer = 0
let g:ctrlp_working_path_mode = 0

" Auto complete
let g:ycm_use_clangd = 0
let g:ycm_use_ultisnips_completer = 1
let g:ycm_seed_identifiers_with_syntax = 1 " Completion for programming language's keyword
let g:ycm_complete_in_comments = 1 " Completion in comments
let g:ycm_complete_in_strings = 1 " Completion in string
let g:ycm_python_binary_path = '/usr/bin/python3' " User python3

let g:ycm_key_list_select_completion = ['<C-j>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-k>', '<Up>']
let g:ycm_auto_trigger = 1
let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_autoclose_preview_window_after_completion = 1

nnoremap gd :YcmCompleter GoToDefinition<CR>
nnoremap gl :YcmCompleter GoToDeclaration<CR>

" Ale
let g:ale_linters_explicit = 1
let g:ale_python_flake8_use_global = 1
let g:ale_linters = {
\   'python': ['flake8', 'pytest'],
\}
let g:ale_fixers = {
\   'python': ['autopep8'],
\}
let g:ale_sign_error = '⨉'
let g:ale_sign_warning = '⬥'
let g:ale_lint_on_enter = 1
let g:ale_open_list = 1
let g:airline#extensions#ale#enabled = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_list_window_size = 8
" let g:ale_python_pylint_options = '--load-plugins pylint_django --disable=C0111,C0301,C0304,C0103,R'

" Auto Format
let g:formatter_yapf_style = 'pep8'

autocmd FileType python setlocal tabstop=4 shiftwidth=4 softtabstop=4 expandtab

" Remap navigations
noremap ; l
noremap l k
noremap k j
noremap j h
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Pydocstring
nmap <silent> <C-_> <Plug>(pydocstring)

" Isort
let g:vim_isort_map = '<C-i>'

" Black
command Black !black -l 79 %:p

" Tagbar
nmap <C-m> :TagbarToggle<CR>
" autocmd VimEnter * nested :TagbarOpen
" autocmd FileType * nested :call tagbar#autoopen(0)
" autocmd BufEnter * nested :call tagbar#autoopen(0)
let g:tagbar_sort = 0

" Fuzzy finder
set rtp+=~/.fzf

" Vim backspace
set backspace=indent,eol,start

" Fold
autocmd Filetype * AnyFoldActivate
set foldlevel=99
